# This file was generated by GoReleaser. DO NOT EDIT.
cask "liftoff" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "445673409c9cfe6b3ec5fb9533c9978d4b72c16b3190b58967adbfd053d1c274"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d21b72acf9dc824b54048a2a6e9e90e3f27785fd7fb172570bd304adb624462c"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "503ef989ffccad99f247a0f961ab3a163c83fed7703dbf8d0967393157e04671"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ab615f33fe6580ea91e271c99362a41859ac6116bc6ea094d10b09b8b20fef11"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_linux_arm64.tar.gz"
    end
  end

  name "liftoff"
  desc "Migrate an IaC estate onto Spacelift"
  homepage "https://github.com/spacelift-solutions/liftoff"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "liftoff-rc",
    ]

  binary "liftoff"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/liftoff"]
    end
  end

  # No zap stanza required

end
