# This file was generated by GoReleaser. DO NOT EDIT.
cask "liftoff" do
  version "1.4.1"

  on_macos do
    on_arm do
      sha256 "7a314b5d5fd433bdad5c18417b0991d2549d3cb37a04651baae4beefdad52fe9"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "92957524f0c1a928b6523a9d7150533ff9552ff649b686c3fcb722f37dd549d9"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "298fdfcfb8ac7fb5d8d45723f5e3ff64dab57df3d40abdbae45d56bcba0834cc"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c41b21c3a0c378caf55d3f6cda1c8e3bfccbf9492f11fe2c40a7f5c0fa22150c"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_linux_amd64.tar.gz"
    end
  end

  name "liftoff"
  desc "Migrate an IaC estate onto Spacelift"
  homepage "https://github.com/spacelift-solutions/liftoff"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "liftoff-rc",
    ]

  binary "liftoff"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/liftoff"]
    end
  end

  # No zap stanza required
end
