# This file was generated by GoReleaser. DO NOT EDIT.
cask "liftoff-rc" do
  version "1.0.0-rc.3"

  on_macos do
    on_intel do
      sha256 "0b8c73ba6552600e14319572ca0bb8a27b85b5ce9207b068d438643d5c4ac4fb"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4b2d29b2218cb97e451d4bc05a1a557ea255ed6357ed6184627e2358472d6e1d"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6b6f58ceb60db9518802067dfbe17787d1bab5db8c7dd79c4189d6fdc23e87ef"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2a38ed93b14528341d5ec65008b21cbb8990c817a3bc486851f4d92cf04155a6"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_linux_arm64.tar.gz"
    end
  end

  name "liftoff-rc"
  desc "Migrate an IaC estate onto Spacelift (release candidate)"
  homepage "https://github.com/spacelift-solutions/liftoff"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "liftoff",
    ]

  binary "liftoff"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/liftoff"]
    end
  end

  # No zap stanza required

end
