# This file was generated by GoReleaser. DO NOT EDIT.
cask "liftoff" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "73f971ce88d9779be6b23b26041147ee4f7299fc8a89a72ee27855c64c4f39e7"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e9a9ac09ec8960e73b9c378873cf63c99c17c9414bc22ad0a917d3b7a2fe0f29"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "47080ddc373ba5c24e36a02a8f0e69221a7a5df47300ff5c6ad642b2c56e360c"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ec86a1bf11dab99c04d647bfb0bccbf37bc95d325c4c71699ce54ac8bbaeab27"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_linux_arm64.tar.gz"
    end
  end

  name "liftoff"
  desc "Migrate an IaC estate onto Spacelift"
  homepage "https://github.com/spacelift-solutions/liftoff"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "liftoff-rc",
    ]

  binary "liftoff"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/liftoff"]
    end
  end

  # No zap stanza required

end
