# This file was generated by GoReleaser. DO NOT EDIT.
cask "liftoff-rc" do
  version "1.0.0-rc.1"

  on_macos do
    on_intel do
      sha256 "7789efa547135ac0c2ae68701a5f26645abd1bd4f51e88986b130b671f8631af"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d3e66120139269fa55bb2474b2eb7fb3a2b92530f8170ecf650ef7de74d7cc97"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5e6b85c81bc56eae61fde78f328a76e150a73fadcc3f3da5d95a578fe2052736"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7e939ec31d0f19caa3500ae08e9d5062ad381cc609d3e92a363c6e19b07594f5"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_linux_arm64.tar.gz"
    end
  end

  name "liftoff-rc"
  desc "Migrate an IaC estate onto Spacelift (release candidate)"
  homepage "https://github.com/spacelift-solutions/liftoff"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "liftoff",
    ]

  binary "liftoff"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/liftoff"]
    end
  end

  # No zap stanza required

end
