# This file was generated by GoReleaser. DO NOT EDIT.
cask "liftoff-rc" do
  version "1.0.0-rc.2"

  on_macos do
    on_intel do
      sha256 "372b67255a03d811e1f621df91e7b5c9aecd5d5adf2220c3447b07b41648e289"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1dcf304671a05da14eb3aef1833f14ef1dd7364e57636e14e174fd6ca3127cfe"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f44b4eec64357287fc2bdeddbc7606bf52d00a526e5c646bbc7b4ff75f7f84b0"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "834e90d2f0d486394183ab88b61d8b5f6cff5567edf06bf263566395fe42aa16"
      url "https://github.com/spacelift-solutions/liftoff/releases/download/v#{version}/liftoff_#{version}_linux_arm64.tar.gz"
    end
  end

  name "liftoff-rc"
  desc "Migrate an IaC estate onto Spacelift (release candidate)"
  homepage "https://github.com/spacelift-solutions/liftoff"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "liftoff",
    ]

  binary "liftoff"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/liftoff"]
    end
  end

  # No zap stanza required

end
